### PR TITLE
Fix ConfigureArquillianTask to use variables in config file.

### LINKED ISSUE #453: Fix configureArquillian task to find http port in generated config variable file
See issue https://github.com/OpenLiberty/ci.maven/issues/713 and related changes in https://github.com/OpenLiberty/ci.maven/pull/806 and https://github.com/OpenLiberty/ci.common/pull/138. Need to pass in the generated liberty-plugin-variable-config.xml to the getHttpPort method in ci.common.

### PR DESCRIPTION
**Pull request by kevinwlau**
Fixes #453

### CODE REVIEW

File: src/test/groovy/io/openliberty/tools/gradle/ConfigureArquillianTest.groovy [hunk 1]
```diff
@@ -1,5 +1,5 @@
 /*
- * (C) Copyright IBM Corporation 2017, 2018.
+ * (C) Copyright IBM Corporation 2017, 2020.
```
Comment (cherylking) [inline src/test/groovy/io/openliberty/tools/gradle/ConfigureArquillianTest.groovy:2]: Doesn't seem like this copyright needed updating?
