### PR TITLE
Detect install changes in dev mode

### LINKED ISSUE #878: Failure to update liberty-plugin-config.xml during Dev Mode startup and after build file changes
Upon starting dev mode, the liberty-plugin-config.xml file does not reflect updates if the file pre-exists. Specifically, changes made to the installDir value within the build.gradle file are not being synchronised into the liberty-plugin-config.xml file. The same behaviour is observed when the installDir value is updated in the build.gradle while dev mode is running. The LMP works as expected in both scenarios, ie. the installDir value is updated in liberty-plugin-config.xml both at startup and while dev mode is running.

### Scenario 1

**Prerequisites:**
- The testing environment is the liberty.gradle.test.wrapper.app project, located at liberty-tools-vscode/src/test/resources/gradle.
- The project should already include a liberty-plugin-config.xml file.

**Steps to Reproduce:**
1. In the build.gradle file, incorporate a custom installDir value. For example, change the installDirectory by adding the following block:
`ext { 
     liberty.installDir = "/Users/dessina/Documents/Workspace/IntelliJ/guide-getting-started/start/myinstalldir/wlp" 
  } `
2. Start the liberty server.
3. Observe that the <installDirectory> value within the liberty-plugin-config.xml file remains unchanged, disregarding the new value specified in build.gradle.

### Scenario 2

**Prerequisites:**
Test environment is set up in the liberty.gradle.test.wrapper.app project, located under liberty-tools-vscode/src/test/resources/gradle.

**Steps to Reproduce:**

1. Perform a project clean operation using the command gradle clean.
2. Start liberty server with the default build.gradle file without modifying any configuration.
3. Modify the build.gradle file by adding a custom configuration. For example, change the installDirectory by adding the following block:
`ext { 
     liberty.installDir = "/Users/dessina/Documents/Workspace/IntelliJ/guide-getting-started/start/myinstalldir/wlp" 
  } `
4. Verify the <installDirectory> value in the liberty-plugin-config.xml file.
5. Observe that the value is not updated to the new path, indicating an issue with the live update functionality.

### PR DESCRIPTION
**Pull request by cherylking**
Fixes #878 (Scenario 2)

Detect changes in Liberty installation configuration during dev mode and throw error.

Need to do something similar in LMP. Will work on the PR next week.

### CODE REVIEW

**Comment by cherylking** [comment]
This is what the logging/error looks like:

Screenshot 2024-02-20 at 10 07 10 AM

File: src/main/groovy/io/openliberty/tools/gradle/tasks/DevTask.groovy [hunk 1]
```diff
@@ -688,6 +699,59 @@ class DevTask extends AbstractFeatureTask {
...
+            // The following project configuration is used for the Liberty installation
+            // liberty extension: installDir, baseDir, cacheDir, outputDir, userDir, runtime
+            // libertyRuntime dependency
+            // liberty->install block: type, runtimeUrl, version, useOpenLiberty
+            boolean foundChange = false
+            if (newProject.liberty.installDir != oldProject.liberty.installDir) {
+                logger.debug('liberty.installDir changed')
+                foundChange = true
+            }
+            if (newProject.liberty.baseDir != oldProject.liberty.baseDir) {
```
Comment (TrevCraw) [inline src/main/groovy/io/openliberty/tools/gradle/tasks/DevTask.groovy:712]: A similar method on the LMP side used an `else-if` pattern and returned `true` as soon as a change was found. Should we follow that strategy here or do we want to make sure to debug every line that was changed?

Comment (cherylking) [reply src/main/groovy/io/openliberty/tools/gradle/tasks/DevTask.groovy:712]: Right...I was trying to give as much feedback as possible if multiple things changed. But I could switch it to just return true on the first change detected. I don't have a problem with that. Let me know if you want me to change it.

Comment (cherylking) [reply src/main/groovy/io/openliberty/tools/gradle/tasks/DevTask.groovy:711]: I changed it. Didn't see the point in an `else-if` pattern, but I did `return true` as soon as an `if` evaluates to `true`.

**Review by TrevCraw — APPROVED** [review]
