### PR TITLE
preventing infinite loop

### LINKED ISSUE #999: Got StackOverflowError when run libertyDev
I got recursive call [this method](https://github.com/OpenLiberty/ci.gradle/blob/7cebb8fea97aa9ae6a5c2cad8544f47b2e804bc5/src/main/groovy/io/openliberty/tools/gradle/utils/DevTaskHelper.groovy#L82-L99).

```
        at org.gradle.api.internal.DelegatingDomainObjectSet.toArray(DelegatingDomainObjectSet.java:170)
        at java_util_Set$toArray.call(Unknown Source)
        at io.openliberty.tools.gradle.utils.DevTaskHelper.getAllUpstreamProjects(DevTaskHelper.groovy:88)
        at io.openliberty.tools.gradle.utils.DevTaskHelper$getAllUpstreamProjects$0.callStatic(Unknown Source)
        at io.openliberty.tools.gradle.utils.DevTaskHelper.getAllUpstreamProjects(DevTaskHelper.groovy:93)
        at io.openliberty.tools.gradle.utils.DevTaskHelper$getAllUpstreamProjects$0.callStatic(Unknown Source)
        at io.openliberty.tools.gradle.utils.DevTaskHelper.getAllUpstreamProjects(DevTaskHelper.groovy:93)
        at io.openliberty.tools.gradle.utils.DevTaskHelper$getAllUpstreamProjects$0.callStatic(Unknown Source)
        at io.openliberty.tools.gradle.utils.DevTaskHelper.getAllUpstreamProjects(DevTaskHelper.groovy:93)
        at io.openliberty.tools.gradle.utils.DevTaskHelper$getAllUpstreamProjects$0.callStatic(Unknown Source)
        at io.openliberty.tools.gradle.utils.DevTaskHelper.getAllUpstreamProjects(DevTaskHelper.groovy:93)
        at io.openliberty.tools.gradle.utils.DevTaskHelper$getAllUpstreamProjects$0.callStatic(Unknown Source)
        at io.openliberty.tools.gradle.utils.DevTaskHelper.getAllUpstreamProjects(DevTaskHelper.groovy:93)
        at io.openliberty.tools.gradle.utils.DevTaskHelper$getAllUpstreamProjects$0.callStatic(Unknown Source)
        at io.openliberty.tools.gradle.utils.DevTaskHelper.getAllUpstreamProjects(DevTaskHelper.groovy:93)
        at io.openliberty.tools.gradle.utils.DevTaskHelper$getAllUpstreamProjects$0.callStatic(Unknown Source)
        at io.openliberty.tools.gradle.utils.DevTaskHelper.getAllUpstreamProjects(DevTaskHelper.groovy:93)
        at io.openliberty.tools.gradle.utils.DevTaskHelper$getAllUpstreamProjects$0.callStatic(Unknown Source)
```

**Steps to produce the problem:**
- `git clone https://github.com/gkwan-ibm/spring-petclinic.git -b lmp-dev-mode`
- `cd spring-petclinic`
- update the `build.gradle` by adding following plugins
```
  id 'war'
  id 'io.openliberty.tools.gradle.Liberty' version '3.9.5'
```
- run `./gradlew libertyDev` and will get
```
* What went wrong:
Execution failed for task ':libertyDev'.
> java.lang.StackOverflowError (no error message)
```
-   run `./gradlew libertyDev --stacktrace` will get the above exception stack traces

**Expectation:**
- can start the dev mode and the petclinic app can be started at http://localhost:8080/

### PR DESCRIPTION
**Pull request by arunvenmany-ibm**
Fixes #999

### CODE REVIEW

File: src/main/groovy/io/openliberty/tools/gradle/utils/DevTaskHelper.groovy [hunk 1]
```diff
@@ -82,15 +82,20 @@ public class DevTaskHelper {
...
+                for (Dependency dependency1 : deployDeps) {
                     if (dependency1 instanceof ProjectDependency) {
                         Project dependencyProject = dependency1.getDependencyProject()
-                        allDependentProjects.add(dependencyProject)
-                        allDependentProjects.addAll(getAllUpstreamProjects(dependencyProject))
+                        //ignore self dependencies and containment's, some configuration such as nativeImageClasspath has containment's
+                        if (dependencyProject != project) {
+                            if (allDependentProjects.add(dependencyProject)) {
+                                // prevent infinite recursion and redundant work, as it only makes the recursive call if a new project is found.
+                                allDependentProjects.addAll(getAllDownstreamProjects(dependencyProject))
```
Comment (cherylking) [inline src/main/groovy/io/openliberty/tools/gradle/utils/DevTaskHelper.groovy:96]: Why is this calling `getAllDownstreamProjects`? Does that exist? This method used to call this method recursively and it is called `getAllUpstreamProjects`.

Comment (arunvenmany-ibm) [reply src/main/groovy/io/openliberty/tools/gradle/utils/DevTaskHelper.groovy]: Yes.. at some point, I was thinking of changing the methodname, but I understood that upstream is the correct naming for projects which are used as libraries in one project. 

corrected
